---
version: 3
images:
  base_image:
    name: rockylinux:9-minimal
options:
  package_manager_path: /usr/bin/microdnf
dependencies:
  python_interpreter:
    package_system: python3.11
  ansible_core:
    # Require minimum of 2.15 to get ansible-inventory --limit option
    package_pip: ansible-core>=2.15.0rc2,<2.16
  ansible_runner:
    package_pip: ansible-runner
  galaxy: |
    ---
    collections:
      - name: amazon.aws
        version: ">=7.0.0"
      - name: ansible.posix
        version: ">=1.5.4"
      - name: ansible.windows
        version: ">=2.2.0"
      - name: awx.awx
        version: ">=23.5.0"
      - name: azure.azcollection
        version: ">=1.19.0"
      - name: community.windows
        version: ">=2.1.0"
      - name: community.vmware
        version: ">=2.15.0"
      - name: kubernetes.core
        version: ">=2.4.0"
      - name: google.cloud
        version: ">=1.3.0"
      - name: openstack.cloud
        version: ">=2.2.0"
      - name: ovirt.ovirt
        version: ">=3.2.0"
      - name: theforeman.foreman
        version: ">=3.15.0"
  system: |
    epel-release [platform:rpm]
    gcc [platform:rpm]
    gcc-c++ [platform:rpm]
    git-core [platform:rpm]
    git-lfs [platform:rpm]
    krb5-devel [platform:rpm compile]
    krb5-workstation [platform:rpm]
    libcurl-devel [platform:rpm compile]
    podman-remote [platform:rpm]
    python3.11-devel [platform:rpm compile]
    python3.11-devel [platform:rpm compile]
    python3.11-rpm [platform:rpm epel]
    python-unversioned-command [platform:rpm]
    rsync [platform:rpm]
    sshpass [platform:rpm]
    unzip [platform:rpm]
    sudo [platform:rpm]
  python: |
    git+https://github.com/ansible/ansible-sign
    ncclient
    paramiko
    pexpect>=4.5
    pykerberos
    pyOpenSSL
    pypsrp[kerberos,credssp]
    python-daemon
    pywinrm[kerberos,credssp]
    pyyaml
    receptorctl
    six
    toml
    boto3
  exclude:
    system:
      - python3
      - python3-devel
      - python3-rpm
additional_build_files:
  - src: sudoers
    dest: configs
additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install -U pip
  append_final:
    - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - ADD _build/configs/sudoers /etc/sudoers
    - >-
      RUN mkdir -p /var/run/receptor /runner
      && git lfs install --system
      && chmod 440 /etc/sudoers
      && useradd -G wheel -M -u 1000 -d /runner ascender
      && chown -R ascender:wheel /runner
      && alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1
      && alternatives --install /usr/bin/python python /usr/bin/python3.11 1
      && alternatives --install /usr/bin/pip3 pip3 /usr/bin/pip3.11 1
      && /usr/bin/microdnf clean all

#    - RUN git lfs install --system
#    - RUN chmod 440 /etc/sudoers
#    - RUN mkdir -p /runner
#    - RUN useradd -G wheel -M -u 1000 -d /runner ascender
#    - RUN chown -R ascender:wheel /runner
    # SymLink `python` -> `python3.11` and `python3` -> `python3.11` and `pip3` -> `pip3.11`
#    - >-
#      RUN alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1
#      && alternatives --install /usr/bin/python python /usr/bin/python3.11 1
#      && alternatives --install /usr/bin/pip3 pip3 /usr/bin/pip3.11 1
